--Peminjam--
--create tabel dosen
CREATE TABLE DOSEN (
ID_Dosen NUMBER(10)NOT  NULL,
NPP NUMBER (16) NOT NULL,
NAMA VARCHAR (20) NOT NULL,
ALAMAT VARCHAR (20),
JUMLAH_PINJAM NUMBER (10),
CONSTRAINT DOSEN_PK PRIMARY KEY (NPP) ENABLE
);
--create tabel mahasiswa
CREATE TABLE MAHASISWA (
ID_MAHASISWA VARCHAR2 (10)NOT  NULL,
NIM NUMBER (9) NOT NULL,
NAMA VARCHAR2 (20) NOT NULL,
ALAMAT VARCHAR2 (20)NOT NULL,
JUMLAH_PINJAM NUMBER (10) NOT NULL,
CONSTRAINT MAHASISWA_PK PRIMARY KEY (NIM) ENABLE
);
--create tabel umum
CREATE TABLE UMUM (
ID_U VARCHAR2 (10)NOT  NULL,
NIK NUMBER (18) NOT NULL,
NAMA VARCHAR2 (20) NOT NULL,
ALAMAT VARCHAR2 (20)NOT NULL,
JUMLAH_PINJAM NUMBER (10) NOT NULL,
CONSTRAINT UMUM_PK PRIMARY KEY (NIK) ENABLE
);

--Clear tabel
TRUNCATE TABLE DOSEN;
--Modify tabel
ALTER TABLE DOSEN MODIFY NAMA VARCHAR2 (20) NOT NULL;
ALTER TABLE DOSEN MODIFY ALAMAT VARCHAR2 (20) NOT NULL;
ALTER TABLE DOSEN MODIFY NPP NUMBER (18) ;
ALTER TABLE DOSEN MODIFY JUMLAH_PINJAM NUMBER (10) ;
ALTER TABLE DOSEN MODIFY ID_DOSEN varchar2 (8);
ALTER TABLE MAHASISWA RENAME COLUMN NAMA TO NAMA_MHS;
ALTER TABLE MAHASISWA RENAME COLUMN ALAMAT TO ALAMAT_MHS;
ALTER TABLE MAHASISWA RENAME COLUMN JUMLAH_PINJAM TO JUMLAH_PINJAM_MHS;


ALTER TABLE DOSEN RENAME COLUMN NAMA TO NAMA_DSN;
ALTER TABLE DOSEN RENAME COLUMN ALAMAT TO ALAMAT_DSN;
ALTER TABLE DOSEN RENAME COLUMN JUMLAH_PINJAM TO JUMLAH_PINJAM_DSN;


ALTER TABLE UMUM RENAME COLUMN NAMA TO NAMA_U;
ALTER TABLE UMUM RENAME COLUMN ALAMAT TO ALAMAT_U;
ALTER TABLE UMUM RENAME COLUMN JUMLAH_PINJAM TO JUMLAH_PINJAM_U;

--Cek tabel
SELECT *FROM DOSEN;
SELECT *FROM MAHASISWA;
SELECT *FROM UMUM;

SELECT * FROM DOSEN,MAHASISWA,UMUM; 
WHERE ID_DOSEN LIKE 'D%'OR ID_MAHASISWA LIKE 'M%'OR ID_U LIKE 'U%';
SELECT * FROM employees,departments;

select * from book;


--Koleksi--
CREATE TABLE BOOK (
ID_BOOK VARCHAR2 (10)NOT  NULL,
JUDUL VARCHAR2 (15) NOT NULL,
PENERBIT VARCHAR2 (20) NOT NULL,
HALAMAN VARCHAR2 (10)NOT NULL,
ISBN NUMBER (15) NOT NULL,
CONSTRAINT BOOK_PK PRIMARY KEY (ID_BOOK) ENABLE
);

CREATE TABLE CD (
ID_DISK VARCHAR2 (10)NOT  NULL,
JUDUL VARCHAR2 (15) NOT NULL,
PENERBIT VARCHAR2 (20) NOT NULL,
FORMAT_DISK VARCHAR2 (10)NOT NULL,
ISBN NUMBER (15) NOT NULL,
CONSTRAINT CD_PK PRIMARY KEY (ID_DISK) ENABLE
);

CREATE TABLE MAJALAH (
ID_MAJALAH VARCHAR2 (10)NOT  NULL,
JUDUL VARCHAR2 (15) NOT NULL,
PENERBIT VARCHAR2 (20) NOT NULL,
VOLUME_MAJALAH NUMBER (10)NOT NULL,
ISBN NUMBER (15) NOT NULL,
CONSTRAINT MAJALAH_PK PRIMARY KEY (ID_MAJALAH) ENABLE
);

--ALTER TABLE MAJALAH MODIFY NAMA VARCHAR2 (20) NOT NULL;

SELECT *FROM CD;
SELECT *FROM BOOK;
SELECT *FROM MAJALAH;

ALTER TABLE CD RENAME COLUMN ID_DISK TO ID_D;
ALTER TABLE CD RENAME COLUMN FORMAT TO FORMAT_D;
ALTER TABLE CD RENAME COLUMN ISBN TO ISBN_D;


ALTER TABLE MAJALAH RENAME COLUMN SERI TO SERI_M;
ALTER TABLE MAJALAH RENAME COLUMN PENERBIT TO PENERBIT_M;
ALTER TABLE MAJALAH RENAME COLUMN VOLUME_MAJALAH TO VOLUME_M;

ALTER TABLE BOOK RENAME COLUMN PENERBIT TO PENERBIT_B;
ALTER TABLE BOOK RENAME COLUMN HALAMAN TO HALAMAN_B;
ALTER TABLE BOOK RENAME COLUMN BOOK TO ISBN_B;

ALTER TABLE BOOK MODIFY HALAMAN_B NUMBER (10);
ALTER TABLE BOOK MODIFY JUDUL_B varchar2 (25);

ALTER TABLE CD RENAME COLUMN HALAMAN TO FORMAT;
ALTER TABLE MAJALAH RENAME COLUMN ISSN TO SERI;
ALTER TABLE MAJALAH ADD (
ISSN NUMBER (15) NOT NULL);


--TABLE TRANSAKSI

CREATE TABLE TRANSAKSI {
ID_TRANSAKSI VARCHAR2 (25) NOT NULL,
TGL_PINJAM DATE 


