CREATE TABLE STOK 
(KODE VARCHAR2 (20) NOT NULL,
NAMA VARCHAR2 (30) NOT NULL,
HARGASATUAN NUMBER (33) NOT NULL,
STOKBARANG NUMBER (33) NOT NULL,
JUMLAHPEMBELIAN NUMBER (33) NOT NULL,
TOTAL NUMBER (33) NOT NULL,
CONSTRAINT KODE_PM PRIMARY KEY ENABLE);

DROP TABLE STOK;

SELECT * FROM STOK;