SELECT * FROM DOSEN;
SELECT * FROM MAHASISWA;
SELECT * FROM UMUM;

SELECT * FROM BOOK;
SELECT * FROM MAJALAH;
SELECT * FROM CD;

TRUNCATE TABLE MAJALAH;
TRUNCATE TABLE BOOK;
TRUNCATE TABLE CD;


